apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: your-namespace
spec:
  limits:
  - types: Pod
    max:
      cpu: "2"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "50Mi"
    default:
      cpu: "200m"
      memory: "100Mi"
    defaultRequest:
      cpu: "100m"
      memory: "50Mi"
    maxLimitRequestRation:
      cpu: "10"



#Purpose: A LimitRange sets default resource limits and requests for containers within Pods if not explicitly specified. It helps in ensuring that Pods have appropriate resource requests and limits set, which can prevent resource contention and ensure optimal resource utilization.
#Scope: It applies to individual Pods within a namespace.
#Limits: LimitRanges typically specify default resource requests and limits for CPU and memory, but can also include other resource types.
#Example: You can set a LimitRange to ensure that every Pod in a namespace has a minimum and maximum CPU and memory allocation, even if these values are not explicitly specified in the Pod manifest.

