apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-app-rc
  labels:
    app: redis-app
spec:
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis

  replicas: 3 
    